/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTemplatesRouteImport } from './routes/app.templates'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPlacementsRouteImport } from './routes/app.placements'
import { Route as AppLogsRouteImport } from './routes/app.logs'
import { Route as AppJobsRouteImport } from './routes/app.jobs'
import { Route as AppInterviewsRouteImport } from './routes/app.interviews'
import { Route as AppInternalAlertsRouteImport } from './routes/app.internal-alerts'
import { Route as AppHealthRouteImport } from './routes/app.health'
import { Route as AppCopilotRouteImport } from './routes/app.copilot'
import { Route as AppCollectionsRouteImport } from './routes/app.collections'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppCandidatesRouteImport } from './routes/app.candidates'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAutomationRouteImport } from './routes/app.automation'
import { Route as ApiPublicSchedulerRunRouteImport } from './routes/api.public.scheduler.run'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacementsRoute = AppPlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsRoute = AppInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AppRoute,
} as any)
const AppInternalAlertsRoute = AppInternalAlertsRouteImport.update({
  id: '/internal-alerts',
  path: '/internal-alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesRoute = AppCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationRoute = AppAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicSchedulerRunRoute = ApiPublicSchedulerRunRouteImport.update({
  id: '/api/public/scheduler/run',
  path: '/api/public/scheduler/run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/automation': typeof AppAutomationRoute
  '/app/billing': typeof AppBillingRoute
  '/app/candidates': typeof AppCandidatesRoute
  '/app/clients': typeof AppClientsRoute
  '/app/collections': typeof AppCollectionsRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/health': typeof AppHealthRoute
  '/app/internal-alerts': typeof AppInternalAlertsRoute
  '/app/interviews': typeof AppInterviewsRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/logs': typeof AppLogsRoute
  '/app/placements': typeof AppPlacementsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/': typeof AppIndexRoute
  '/api/public/scheduler/run': typeof ApiPublicSchedulerRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/automation': typeof AppAutomationRoute
  '/app/billing': typeof AppBillingRoute
  '/app/candidates': typeof AppCandidatesRoute
  '/app/clients': typeof AppClientsRoute
  '/app/collections': typeof AppCollectionsRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/health': typeof AppHealthRoute
  '/app/internal-alerts': typeof AppInternalAlertsRoute
  '/app/interviews': typeof AppInterviewsRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/logs': typeof AppLogsRoute
  '/app/placements': typeof AppPlacementsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app': typeof AppIndexRoute
  '/api/public/scheduler/run': typeof ApiPublicSchedulerRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/automation': typeof AppAutomationRoute
  '/app/billing': typeof AppBillingRoute
  '/app/candidates': typeof AppCandidatesRoute
  '/app/clients': typeof AppClientsRoute
  '/app/collections': typeof AppCollectionsRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/health': typeof AppHealthRoute
  '/app/internal-alerts': typeof AppInternalAlertsRoute
  '/app/interviews': typeof AppInterviewsRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/logs': typeof AppLogsRoute
  '/app/placements': typeof AppPlacementsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/': typeof AppIndexRoute
  '/api/public/scheduler/run': typeof ApiPublicSchedulerRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/app/automation'
    | '/app/billing'
    | '/app/candidates'
    | '/app/clients'
    | '/app/collections'
    | '/app/copilot'
    | '/app/health'
    | '/app/internal-alerts'
    | '/app/interviews'
    | '/app/jobs'
    | '/app/logs'
    | '/app/placements'
    | '/app/reports'
    | '/app/settings'
    | '/app/templates'
    | '/app/'
    | '/api/public/scheduler/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/app/automation'
    | '/app/billing'
    | '/app/candidates'
    | '/app/clients'
    | '/app/collections'
    | '/app/copilot'
    | '/app/health'
    | '/app/internal-alerts'
    | '/app/interviews'
    | '/app/jobs'
    | '/app/logs'
    | '/app/placements'
    | '/app/reports'
    | '/app/settings'
    | '/app/templates'
    | '/app'
    | '/api/public/scheduler/run'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/app/automation'
    | '/app/billing'
    | '/app/candidates'
    | '/app/clients'
    | '/app/collections'
    | '/app/copilot'
    | '/app/health'
    | '/app/internal-alerts'
    | '/app/interviews'
    | '/app/jobs'
    | '/app/logs'
    | '/app/placements'
    | '/app/reports'
    | '/app/settings'
    | '/app/templates'
    | '/app/'
    | '/api/public/scheduler/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicSchedulerRunRoute: typeof ApiPublicSchedulerRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/placements': {
      id: '/app/placements'
      path: '/placements'
      fullPath: '/app/placements'
      preLoaderRoute: typeof AppPlacementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/interviews': {
      id: '/app/interviews'
      path: '/interviews'
      fullPath: '/app/interviews'
      preLoaderRoute: typeof AppInterviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/internal-alerts': {
      id: '/app/internal-alerts'
      path: '/internal-alerts'
      fullPath: '/app/internal-alerts'
      preLoaderRoute: typeof AppInternalAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/health': {
      id: '/app/health'
      path: '/health'
      fullPath: '/app/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/copilot': {
      id: '/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/collections': {
      id: '/app/collections'
      path: '/collections'
      fullPath: '/app/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/candidates': {
      id: '/app/candidates'
      path: '/candidates'
      fullPath: '/app/candidates'
      preLoaderRoute: typeof AppCandidatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/automation': {
      id: '/app/automation'
      path: '/automation'
      fullPath: '/app/automation'
      preLoaderRoute: typeof AppAutomationRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/scheduler/run': {
      id: '/api/public/scheduler/run'
      path: '/api/public/scheduler/run'
      fullPath: '/api/public/scheduler/run'
      preLoaderRoute: typeof ApiPublicSchedulerRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAutomationRoute: typeof AppAutomationRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCandidatesRoute: typeof AppCandidatesRoute
  AppClientsRoute: typeof AppClientsRoute
  AppCollectionsRoute: typeof AppCollectionsRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppHealthRoute: typeof AppHealthRoute
  AppInternalAlertsRoute: typeof AppInternalAlertsRoute
  AppInterviewsRoute: typeof AppInterviewsRoute
  AppJobsRoute: typeof AppJobsRoute
  AppLogsRoute: typeof AppLogsRoute
  AppPlacementsRoute: typeof AppPlacementsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAutomationRoute: AppAutomationRoute,
  AppBillingRoute: AppBillingRoute,
  AppCandidatesRoute: AppCandidatesRoute,
  AppClientsRoute: AppClientsRoute,
  AppCollectionsRoute: AppCollectionsRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppHealthRoute: AppHealthRoute,
  AppInternalAlertsRoute: AppInternalAlertsRoute,
  AppInterviewsRoute: AppInterviewsRoute,
  AppJobsRoute: AppJobsRoute,
  AppLogsRoute: AppLogsRoute,
  AppPlacementsRoute: AppPlacementsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicSchedulerRunRoute: ApiPublicSchedulerRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
